spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties.hibernate:
      format_sql: true
  application:
    name: BankingTestAPI
server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    oauth:
      client-id: client-id
      client-secret: client-secret
      token-url: http://localhost:9000/oauth2/token

logging:
  level:
    org:
      springframework:
        security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false  # <--- This forces Spring to remove any actuator security
  endpoint:
    health:
      show-details: always


jwt:
  secret: ${JWT_SECRET_KEY}

security:
  roles:
    public:
      - "/api/auth/**"
      - "/swagger-ui/**"
      - "/v3/api-docs/**"
    user:
      - "/api/user/**"
      - "/api/deposits"
    admin:
      - "/**"  # Admin has access to everything
    agent:
      - "/**"  # Agent has access to everything


