spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties.hibernate:
      format_sql: true
  application:
    name: BankingTestAPI
server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    oauth:
      client-id: client-id
      client-secret: client-secret
      token-url: http://localhost:9000/oauth2/token

oauth2:
  client:
    id: ${OAUTH2_CLIENT_ID:default-client-id}
    secret: ${OAUTH2_CLIENT_SECRET:default-client-secret}
