name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Change this if you use another branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up JDK 17 (to build your project with Gradle)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # 3. Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # 4. Set up Docker Buildx (optional but useful for building images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 5. Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: milindp25/banking-test-api:${{ github.sha }}

      # 7. Deploy to EC2 via SSH
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            # Pull the new Docker image
            docker pull milindp25/banking-test-api:${{ github.sha }}

            # Stop and remove the old container (if it exists)
            docker stop yourapp || true
            docker rm yourapp || true

            # Run the new container with environment variables
            docker run -d \
              --name yourapp \
              -p 8080:8080 \
              -e DB_URL="${{ secrets.DB_URL }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              milindp25/banking-test-api:${{ github.sha }}
