name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Make gradlew executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 3. Set up Amazon Corretto 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # 4. Build with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # 5. Set up Docker Buildx (optional, but recommended)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 6. Log in to Docker Hub (or any other registry)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: milindp25/banking-test-api:${{ github.sha }}

      # 8. Deploy to EC2 via SSH
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            # Pull the new Docker image
            docker pull milindp25/banking-test-api:${{ github.sha }}

            # Stop and remove any existing container
            docker stop yourapp || true
            docker rm yourapp || true

            # Run the new container with environment variables
            docker run -d \
              --name yourapp \
              -p 8080:8080 \
              -e DB_URL="${{ secrets.DB_URL }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              milindp25/banking-test-api:${{ github.sha }}
