name: Deploy Spring Boot to AWS EC2

on:
  push:
    branches:
      - main  # Change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant Execute Permission to Gradle Wrapper  # FIX ADDED HERE
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Transfer JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ec2-user/app"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/app
            echo "Stopping old application (if running)..."
            sudo pkill -f 'java -jar' || true
            sleep 5

            echo "Deleting old JAR files..."
            rm -f *.jar

            echo "Moving latest JAR from build/libs to app directory..."
            mv build/libs/Banking-Test-API-0.0.1-SNAPSHOT.jar /home/ec2-user/app/

            echo "Starting new application..."
            nohup java -jar /home/ec2-user/app/Banking-Test-API-0.0.1-SNAPSHOT.jar > app.log 2>&1 &

            echo "Deployment successful!"
      
